/**
 * Report Types - TypeScript interfaces for health/DNA analysis reports
 */

export interface Report {
  reportId: string;
  orderId: string;
  userId: string;
  userName: string;
  userEmail: string;
  
  // Report generation metadata
  generatedAt: string; // ISO timestamp
  updatedAt: string; // ISO timestamp
  status: 'generating' | 'completed' | 'failed';
  
  // Report content (generated by Gemini AI)
  title: string;
  summary: string; // Brief overview
  sections: ReportSection[]; // Detailed analysis sections
  recommendations: string[]; // Health/lifestyle recommendations
  conclusions: string; // Final conclusions
  
  // Raw report content for full text
  fullContent: string;
  
  // Error tracking
  error?: string;
}

export interface ReportSection {
  title: string;
  content: string;
  subsections?: ReportSubsection[];
}

export interface ReportSubsection {
  title: string;
  content: string;
}

export interface ReportGenerationInput {
  orderId: string;
  orderData: any; // Complete order form data with all questionnaire answers
  userName: string;
  userEmail: string;
}
